### ISSUE TITLE
Official example chat server crashed when the room creator leave

### ISSUE THREAD

**Issue by FredDull** [gamestdio/colyseus#127]
user A join (create) the room;
user B join the room;
they chat;
user A leave (close the browser);
then the server crashes.
![error](https://user-images.githubusercontent.com/12006286/36337960-f8005e46-13dd-11e8-8e8c-656250250b5e.JPG)

**Comment by FredDull** [comment]
Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:569:26)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by endel** [comment]
Hi @FredDull, 

Sorry, the `package-lock.json` file was locking a previous version (`colyseus@0.8.1`).

This error has been fixed in recent versions. I've just updated the `package-lock.json` file from `colyseus-examples` to use the most recent one (`colyseus@0.8.11`). You can pull the latest version of it and install the dependencies again, then this error should be gone.

Thanks for letting me know,
Cheers!
