### ISSUE TITLE
Allow disabling automatic patches

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus#138]
There are some use cases that state sync is not necessary at all.

Currently, the following doesn't have the expected behavior:

```
this.setPatchRate(null);
this.setPatchRate(0);
```

By passing such values on `setPatchRate`, the [automatic patch broadcasts](https://github.com/gamestdio/colyseus/blob/f3f0c217eed04a0c1a44821a833954675b85971f/src/Room.ts#L231) should be disabled.

**Comment by terranblake** [comment]
@endel I am looking into this issue as my first pull request, and am wondering if the following test is sufficient for the expected behavior that you are looking to reconcile in this issue?

`it('should disable "patch" interval', function () {
      var room = new DummyRoom();
      room.setPatchRate(null);

      assert.equal("object", typeof ((<any>room)._patchInterval));
      assert.equal(-1, (<any>room)._patchInterval._idleTimeout, "patch rate should be disabled, set to -1");
    });`

Where `-1` is the resultant value after using `clearTimeout()` to disable the patch timer. I believe I have a fix, and it does pass this test, but I'm not sure if I am missing something.

**Comment by terranblake** [comment]
I have also tested this using the `colyseus-examples` repository, which resulted in successfully disabling the patch timer. All other tests continue to pass.

**Comment by GAMEKON** [comment]
what about

use patchRate property instead of setPatchRate() method.¶
OLD


constructor (options) {
  this.setPatchRate(1000 / 50);
}
NEW


class MyRoom extends Room {
  patchRate = 1000 / 50;
}
