### ISSUE TITLE
warning " > colyseus@0.9.9" has unmet peer dependency "uws@^9.14.0"

### ISSUE THREAD

**Issue by ellipticaldoor** [gamestdio/colyseus#159]
When I install colyseus I get this warning:

``` shell
warning " > colyseus@0.9.9" has unmet peer dependency "uws@^9.14.0".
```

It looks like colyseus is working but Im not sure if this can be a problem.

**Comment by seiyria** [comment]
This is intentional, `uws` is an optional dependency. Colyseus uses `ws` by default.

**Comment by ellipticaldoor** [comment]
What do you recommend?

On the example is only installed the types for uws

**Comment by seiyria** [comment]
Uws is always the best choice if you can use it.

On May 27, 2018 12:43 PM, "Miguel Dorta" <notifications@github.com> wrote:

What do you recommend?

On the example is only installed the types for uws

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/gamestdio/colyseus/issues/159#issuecomment-392350236>,
or mute the thread

**Comment by ellipticaldoor** [comment]
And to use it I only have to install it as dependency?

**Comment by seiyria** [comment]
You'll also have to specify it as the engine. You can find examples of how
to do that somewhere.

On May 27, 2018 1:04 PM, "Miguel Dorta" <notifications@github.com> wrote:

And to use it I only have to install it as dependency?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/gamestdio/colyseus/issues/159#issuecomment-392351514>,
or mute the thread

**Comment by ellipticaldoor** [comment]
Here it is http://colyseus.io/docs/api-server/#optionsengine

Thank you

**Comment by ellipticaldoor** [comment]
On the client I don't have to do nothing right?

**Comment by seiyria** [comment]
Correct.

On May 27, 2018 1:10 PM, "Miguel Dorta" <notifications@github.com> wrote:

On the client I don't have to do nothing right?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/gamestdio/colyseus/issues/159#issuecomment-392351902>,
or mute the thread

**Comment by ellipticaldoor** [comment]
I installed latest uws but I still get a warning:

> warning " > colyseus@0.9.9" has incorrect peer dependency "uws@^9.14.0".

It looks like the server works fine

**Comment by endel** [comment]
`uws` has been removed from the dependencies, since it has been unpublished by it's author from NPM.
