### ISSUE TITLE
Problem when running with new workers implementation

### ISSUE THREAD

**Issue by Tazer** [gamestdio/colyseus#67]
Seems it losing context between processes or something ( I have told it to spawn several processes either). I'm just running forever start index.js and this error occures when the client tries to join. I'm using 0.7.0-alpha.3 on the client with: client.join('room'); , a note is that it works fine "localhost", this is behind an nginx. But tried the "stable" version and they worked fine with the nginx config. but got into some other problems with that. So would need to run the latest versions :)
```
data:    dist/index.js:6306 - process wants to communicate directly with pid (6320)
data:    dist/index.js:6306 - process 6320 is responding to JOIN_ROOM
data:    dist/index.js:6306 - process wants to communicate directly with pid (6321)
data:    dist/index.js:6306 - /var/www/c-c-c-combo/backend/node_modules/colyseus/lib/MatchMaker.js:85
data:    dist/index.js:6306 -         client.sessionId = clientOptions.sessionId;
data:    dist/index.js:6306 -                                         ^
data:    dist/index.js:6306 - TypeError: Cannot read property 'sessionId' of undefined
data:    dist/index.js:6306 -     at MatchMaker.onJoin (/var/www/c-c-c-combo/backend/node_modules/colyseus/lib/MatchMaker.js:85:41)
data:    dist/index.js:6306 -     at Server.<anonymous> (/var/www/c-c-c-combo/backend/node_modules/colyseus/lib/cluster/Worker.js:41:20)
data:    dist/index.js:6306 -     at emitOne (events.js:96:13)
data:    dist/index.js:6306 -     at Server.emit (events.js:188:7)
data:    dist/index.js:6306 -     at Server.emitConnection [as _upgradeCallback] (/var/www/c-c-c-combo/backend/node_modules/uws/uws.js:15:10)
data:    dist/index.js:6306 -     at Server.native.server.group.onConnection (/var/www/c-c-c-combo/backend/node_modules/uws/uws.js:465:18)
data:    dist/index.js:6306 -     at Socket.socket.on (/var/www/c-c-c-combo/backend/node_modules/uws/uws.js:502:32)
data:    dist/index.js:6306 -     at emitOne (events.js:101:20)
data:    dist/index.js:6306 -     at Socket.emit (events.js:188:7)
data:    dist/index.js:6306 -     at TCP._handle.close [as _onclose] (net.js:497:12)
```

**Comment by Tazer** [comment]
Maybe something like this is needed ? https://github.com/indutny/sticky-session  ( https://socket.io/docs/using-multiple-nodes/ )

**Comment by Tazer** [comment]
I did get it working with this commit: https://github.com/Tazer/colyseus/commit/eac8ead586de5e0b223bbd0b74d711ffa94f871d

But guess that breaks other stuff :)

**Comment by endel** [comment]
Hey @Tazer, thanks for sharing, can you share your nginx configuration as well? I'm afraid there's more than one "master" process running.

**Comment by Tazer** [comment]
Here is my nginx conf:

```
server {

 listen 443 ssl http2;
    server_name domain.com;

ssl_certificate /etc/letsencrypt/live/cert/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/cert/privkey.pem;

    # Your favorite resolver may be used instead of the Google one below
    resolver 8.8.8.8;
    location /basic_status {
         stub_status;
    }

    location / {
        proxy_pass http://localhost:3553;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```
After my "ugly" fix, it worked but still had problems that after a while I got the "BUFFER_SHORTAGE". So solve that I also added:

```
        proxy_read_timeout 86400s; 
        proxy_send_timeout 86400s;
```

That solved the problem so it keeps the socket open for more then 1 mintue. But don't think the read/send timeout fixes the problem with `Cannot read property 'sessionId' of undefined`

Cause I still see this in my logs:

```
data:    dist/index.js:27478 - process wants to communicate directly with pid (27486)
data:    dist/index.js:27478 - process 27486 is responding to JOIN_ROOM
data:    dist/index.js:27478 - process wants to communicate directly with pid (27487)
data:    dist/index.js:27478 - whats the message [ 13, 'SkxeBXTuEb', { name: 'Jonis', score: 12 } ]
```

( It's me that added the whats the message log ) but isn't the "master" process `27478` and in my first example `6306` ? and 27486 & 27487 is just workers ?

**Comment by endel** [comment]
I couldn't reproduce the problem here. :( 

**nginx version:** nginx/1.12.0
**node:** v6.9.1
**operational system:** OSX 10.12.5

I've tried a simpler Nginx configuration though:

```
server {
    listen 3553;
    server_name localhost;

    location / {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
```

**To explain what's going on the match-making process:**

I'll try to explain briefly how the match-making process works, which is highly related to this problem.

One WebSocket connection ([`Client.ts`](https://github.com/gamestdio/colyseus.js/blob/f94f703b594319d6078f9656ab20cee76530df26/src/Client.ts)) is used to request the room the client should connect to, and the second is to actually communicate with that room ([`Room.ts`](https://github.com/gamestdio/colyseus.js/blob/f94f703b594319d6078f9656ab20cee76530df26/src/Room.ts)), based on the room `id` received on the first request. Each `client.join("room")` results in a new WebSocket connection.

When the first connection requests to join into a room (`client.join("room")`), the server will either send an `REQUEST_JOIN_ROOM` message to the workers that have that room spawned or send a `CREATE_ROOM` to a random worker.

**First connection: (Client)**

- The master process sends an `CREATE_ROOM` request to the workers, containing the `joinOptions` - ([matchmaking/Process.ts#L160](https://github.com/gamestdio/colyseus/blob/fd7206f8be3c2ce517c6b3dfdb074eb14f911d2d/src/matchmaking/Process.ts#L160))
- The worker stores the `joinOptions` locally on its process memory. ([MatchMaker.ts#L74](https://github.com/gamestdio/colyseus/blob/fd7206f8be3c2ce517c6b3dfdb074eb14f911d2d/src/MatchMaker.ts#L74)) - which should be available later for the second connection.

**Second connection: (Room)**

- The server identifies the room `id` in the URL, and forward the connection to the worker holding the room instance. ([ClusterServer.ts#L61-L74](https://github.com/gamestdio/colyseus/blob/fd7206f8be3c2ce517c6b3dfdb074eb14f911d2d/src/ClusterServer.ts#L61-L74))
- The server tries to effectively join the client into the room, based on the `joinOptions` stored in the previous request ([MatchMaker.ts#L88](https://github.com/gamestdio/colyseus/blob/fd7206f8be3c2ce517c6b3dfdb074eb14f911d2d/src/MatchMaker.ts#L88))

As I couldn't reproduce, I suspect either [`client.id`](https://github.com/gamestdio/colyseus/blob/fd7206f8be3c2ce517c6b3dfdb074eb14f911d2d/src/MatchMaker.ts#L88) is not available for some reason, or the `joinOptions` are not being sent.

Please let me know if you can debug this somehow

**Comment by Tazer** [comment]
Thanks alot for the explanation. 
I will try debugging some later tonight hopefully and get back here if I can find anything.

**Comment by Tazer** [comment]
Okey I did some more debugging. Didn't solve the problem but have some more information at least.
So what I did was to add console before the code crashed, you can see how/what I log here: https://github.com/Tazer/colyseus/blob/93ee8272b370b43740c1858c7eb6c942ea0c76c7/src/MatchMaker.ts#L93 

Below is the result of the logs. and the thing is that both roomID & clientID is set. But it seems they don't match. Cause it seems the clientID doesn't exist in any rooms. But I havn't done anything special. 

```
data:    dist/index.js:17510 - error undefined room SklVXkmxBb clientid Hyxc4ymxHW clientOptions undefined
data:    dist/index.js:17510 - array { SklVXkmxBb:
data:    dist/index.js:17510 -    { HyVQJQxrb: { clientId: 'HyVQJQxrb', sessionId: 'HJ-Vm1mlBb' },
data:    dist/index.js:17510 -      S1tV1XgHZ: { clientId: 'S1tV1XgHZ', sessionId: 'HyqNyXgB-' } } }
```

Do you have any clues @endel ? Feels like some race condition or something.

Just a side note is that it works fine on localhost.

**Comment by endel** [comment]
Thanks for debugging and sharing @Tazer! 

It seems to me that the `clientId` is being re-generated in the second connection - when it should be re-using from the cookie set in the first connection.(https://github.com/gamestdio/colyseus/blob/master/src/cluster/Worker.ts#L16-L25)

I'll try to set up the same environment today as an attempt to reproduce. Please let me know if you have the chance to debug this as well.

**Comment by endel** [comment]
Hey @Tazer,

I've just released a new server & client with a fix for this. The cookie wasn't being forwarded from nginx to node.js for some reason (probably the domain in the cookie wasn't matching)

To avoid unnecessary complexity I've removed this cookie parsing. Now the `roomId` and `colyseusid` are being sent through the connection URL (`ws://endpoint:port/roomId?colyseusid=id`)

New versions are: 
- `colyseus@0.5.0-alpha.9`
- `colyseus.js@0.7.0-alpha.5`

Let me know if it works for you!

**Comment by Tazer** [comment]
@endel , Thanks a lot your fix is working! 👍  If your interested what we do with colyseus check out https://landing.cccombo.com

**Comment by endel** [comment]
@Tazer I thank you :) very interesting! I'm about to publish a blog post this month with a couple of games, may I use yours + link to your GitHub profile there (or another link of your choice)?

**Comment by Tazer** [comment]
Absolutely, sounds great. You can absolutely do that 👌
