### ISSUE TITLE
Keep user state upon reconnection

### ISSUE THREAD

**Issue by takaaptech** [gamestdio/colyseus#8]
Hi again :) , i am playing with https://github.com/endel/tic-tac-toe and i see that sometime one client maybe lost connection (While users are on the go, the data source will often switch towers and or downgrade/upgrade between 2G and 3G).
So i think if server hold the client session, then when client want to re connect, they can send that session id again to go to current playing room.
(i really do not know detail of that feature , but some where they are using ping and pong message between client and server to find if client lost connection or not)
It is very importance in real online game, so it is awesome if we have that feature!
Thanks so much!

**Comment by endel** [comment]
Hey @takaaptech, thanks for checking out the tic-tac-toe demo!

I never experienced this switch you mentioned, are you sure the connection is lost because of this switch?

I'm not sure how to deal with authentic disconnects in parallel with lost connections. Maybe a good idea would be to wait, say, 10 seconds after any disconnection, and only trigger the disconnection handler in case nobody tries to reconnect with that session id during this period.

**Comment by takaaptech** [comment]
Hi, switching between 2G/3G or 3G and wifi cause change ip address maybe the point! I need to build corona sdk tic tac toe version and then deploy to mobile for test now :)

**Comment by endel** [comment]
Closing this feature as it doesn't seem to be relevant. Please feel free to reopen it if you think this is important for your project.
