### ISSUE TITLE
Javascript instead of TypeScript

### ISSUE THREAD

**Issue by gregmax17** [gamestdio/colyseus#80]
How do I tell it use/read the js files instead of the ts files?

**Comment by Federkun** [comment]
Hi @gregmax17, sorry, I'm not sure what do you mean with that. Can you be more clear?

**Comment by gregmax17** [comment]
Im just trying to wrap my head around all of this still, apologizes.

I download this repo and got it running, and it says `starting 'ts-node usage/Server.ts`. I would like to write in a js and use that. 

Off topic, just now I tried creating a `BattleRoom` class... its basically a copy and replace of the `ChatRoom`. But I get this error:

```/Users/gregory/Documents/Curious Media/colyseus/server/src/MatchMaker.ts:188
      , handler = this.handlers[ roomName ][0]```

**Comment by endel** [comment]
Hey @gregmax17,

You'll usually install `colyseus` as a node module, instead of cloning its repository. You can see the [colyseus-examples](https://github.com/gamestdio/colyseus-examples) repository for usage examples. If you'd like to use JavaScript instead of TypeScript, you can grab the compiled JavaScript files from colyseus-examples after compiling (by using `tsc`) and use them instead.

**Comment by endel** [comment]
@gregmax17 feel free to reopen this if you have any other question!
