### ISSUE TITLE
Allow to sending different room's state in function of the client.

### ISSUE THREAD

**Issue by Federkun** [gamestdio/colyseus#88]
I'm in need to sending different room's state in function of each client. The room contains "Red team" members and "Blue team" members. The red team will see just a portion of the room's state, so the blue team.

Right now I don't think there's a clean way to do it: you could manually filter the state for each client when you are broadcasting it using Room#send, without sending incremental patch, but that's inefficient and require more boilerplate code.

Is this use case something worth working on to add as feature in the next minor version, or it's something that you'd consider "too specific" to consider? How'd you handle this now?

**Comment by endel** [comment]
Hey @Federkun,

That's indeed the most requested feature (https://github.com/gamestdio/colyseus/issues/59) I'm not sure yet how to allow this, I'm afraid the whole patch mechanism would need to be changed to allow this - without using delta patches. 

Since a different data-set would need to be used for calculating the diffs (per team, or per user, depending on the use-case), this would increase considerably the CPU usage on the server-side.
